/*
 * AddCurtainShop.java
 *
 * Created on __DATE__, __TIME__
 */

package com.zqw.ui;

import javax.swing.JOptionPane;

import com.zqw.bean.Global;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 * 
 * @author __USER__
 */
public class AddGoodsShop extends javax.swing.JDialog {

	/** Creates new form AddCurtainShop */
	public AddGoodsShop(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		getContentPane().setLayout(null);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setBounds(28, 35, 42, 15);
		serialNumber = new javax.swing.JTextField();
		serialNumber.setBounds(74, 32, 137, 21);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setBounds(28, 62, 42, 15);
		purchasePrice = new javax.swing.JTextField();
		purchasePrice.setBounds(74, 59, 137, 21);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setBounds(29, 89, 42, 15);
		factory = new javax.swing.JTextField();
		factory.setBounds(75, 86, 136, 21);
		add = new javax.swing.JButton();
		add.setBounds(47, 175, 57, 23);
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setBounds(29, 116, 42, 15);
		telephone = new javax.swing.JTextField();
		telephone.setBounds(75, 113, 136, 21);
		jButton1 = new javax.swing.JButton();
		jButton1.setBounds(122, 175, 57, 23);

		// setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("\u578b \u53f7\uff1a");

		jLabel2.setText("\u8fdb \u4ef7\uff1a");

		jLabel3.setText("\u5382 \u5bb6\uff1a");

		add.setText("\u6dfb\u52a0");
		add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addActionPerformed(evt);
			}
		});

		jLabel4.setText("\u7535 \u8bdd\uff1a");
		getContentPane().add(jLabel4);

		jButton1.setText("\u5173\u95ed");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		label = new JLabel();
		label.setBounds(29, 147, 42, 15);
		label.setText("数量：");
		getContentPane().add(label);

		number = new JTextField();
		number.setBounds(75, 144, 136, 21);
		getContentPane().setLayout(null);
		getContentPane().add(number);
		getContentPane().add(jLabel2);
		getContentPane().add(purchasePrice);
		getContentPane().add(jLabel1);
		getContentPane().add(serialNumber);
		getContentPane().add(telephone);
		getContentPane().add(jLabel3);
		getContentPane().add(factory);
		getContentPane().add(add);
		getContentPane().add(jButton1);

	}// </editor-fold>
		// GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void addActionPerformed(java.awt.event.ActionEvent evt) {
		if (serialNumber.getText().trim().length() != 0) {
			Global.goods.setSerialNumber(serialNumber.getText());
		} else {
			JOptionPane.showMessageDialog(this, "请输入型号", "alert",
					JOptionPane.ERROR_MESSAGE);
			Global.goods = null;
			this.dispose();
			return;
		}
		if (purchasePrice.getText().trim().length() != 0) {
			Global.goods.setPurchasePrice(Double.parseDouble(purchasePrice
					.getText().trim()));
		} else {
			Global.goods = null;
			JOptionPane.showMessageDialog(this, "请输入价格", "alert",
					JOptionPane.ERROR_MESSAGE);
			this.dispose();
			return;
		}
		if (factory.getText().trim().length() != 0) {
			Global.goods.setFactory(factory.getText().trim());
		} else {
			Global.goods = null;
			JOptionPane.showMessageDialog(this, "请输入厂家", "alert",
					JOptionPane.ERROR_MESSAGE);
			this.dispose();
			return;
		}
		if (telephone.getText().trim().length() != 0) {
			Global.goods.setTelephone(telephone.getText().trim());
		} else {
			Global.goods = null;
			JOptionPane.showMessageDialog(this, "请输入电话", "alert",
					JOptionPane.ERROR_MESSAGE);
			this.dispose();
			return;
		}
		if (number.getText().trim().length() != 0) {
			Global.goods.setNumber(number.getText().trim());
		} else {
			Global.goods = null;
			JOptionPane.showMessageDialog(this, "请输入电话", "alert",
					JOptionPane.ERROR_MESSAGE);
			this.dispose();
			return;
		}
		this.dispose();
	}

	// /**
	// * @param args
	// * the command line arguments
	// */
	// public static void main(String args[]) {
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// AddGoodsShop dialog = new AddGoodsShop(
	// new javax.swing.JFrame(), true);
	// dialog.addWindowListener(new java.awt.event.WindowAdapter() {
	// public void windowClosing(java.awt.event.WindowEvent e) {
	// System.exit(0);
	// }
	// });
	// dialog.setVisible(true);
	// }
	// });
	// }

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton add;
	private javax.swing.JTextField factory;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField purchasePrice;
	private javax.swing.JTextField serialNumber;
	private javax.swing.JTextField telephone;
	private JLabel label;
	private JTextField number;
	// End of variables declaration//GEN-END:variables

}