/*
 * AddCurtainShop.java
 *
 * Created on __DATE__, __TIME__
 */

package com.zqw.ui;

import javax.swing.JOptionPane;

import com.zqw.bean.Global;

/**
 * 
 * @author __USER__
 */
public class AddGoodsShop extends javax.swing.JDialog {

	/** Creates new form AddCurtainShop */
	public AddGoodsShop(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		serialNumber = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		purchasePrice = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		factory = new javax.swing.JTextField();
		add = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		telephone = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("\u578b \u53f7\uff1a");

		jLabel2.setText("\u8fdb \u4ef7\uff1a");

		jLabel3.setText("\u5382 \u5bb6\uff1a");

		add.setText("\u6dfb\u52a0");
		add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addActionPerformed(evt);
			}
		});

		jLabel4.setText("\u7535 \u8bdd\uff1a");

		jButton1.setText("\u5173\u95ed");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(28, 28, 28)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel2)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		purchasePrice,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		137,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		serialNumber))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(1, 1, 1)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel4)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										telephone,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										136,
																										Short.MAX_VALUE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										factory))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(13,
																										13,
																										13)
																								.addComponent(
																										add)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										jButton1)))))
								.addContainerGap(28, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(32, 32, 32)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														serialNumber,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														purchasePrice,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(6, 6, 6)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														factory,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														telephone,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										32, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(add))
								.addContainerGap()));

		pack();

	}// </editor-fold>
		// GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void addActionPerformed(java.awt.event.ActionEvent evt) {
		if (serialNumber.getText().trim().length() != 0) {
			Global.goods.setSerialNumber(serialNumber.getText());
		} else {
			JOptionPane.showMessageDialog(this, "请输入型号", "alert",
					JOptionPane.ERROR_MESSAGE);
			Global.goods = null;
			this.dispose();
			return;
		}
		if (purchasePrice.getText().trim().length() != 0) {
			Global.goods.setPurchasePrice(Double.parseDouble(purchasePrice
					.getText().trim()));
		} else {
			Global.goods = null;
			JOptionPane.showMessageDialog(this, "请输入价格", "alert",
					JOptionPane.ERROR_MESSAGE);
			this.dispose();
			return;
		}
		if (factory.getText().trim().length() != 0) {
			Global.goods.setFactory(factory.getText().trim());
		} else {
			Global.goods = null;
			JOptionPane.showMessageDialog(this, "请输入厂家", "alert",
					JOptionPane.ERROR_MESSAGE);
			this.dispose();
			return;
		}
		if (telephone.getText().trim().length() != 0) {
			Global.goods.setTelephone(telephone.getText().trim());
		} else {
			Global.goods = null;
			JOptionPane.showMessageDialog(this, "请输入电话", "alert",
					JOptionPane.ERROR_MESSAGE);
			this.dispose();
			return;
		}
		this.dispose();
	}

	// /**
	// * @param args
	// * the command line arguments
	// */
	// public static void main(String args[]) {
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// AddGoodsShop dialog = new AddGoodsShop(
	// new javax.swing.JFrame(), true);
	// dialog.addWindowListener(new java.awt.event.WindowAdapter() {
	// public void windowClosing(java.awt.event.WindowEvent e) {
	// System.exit(0);
	// }
	// });
	// dialog.setVisible(true);
	// }
	// });
	// }

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton add;
	private javax.swing.JTextField factory;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField purchasePrice;
	private javax.swing.JTextField serialNumber;
	private javax.swing.JTextField telephone;
	// End of variables declaration//GEN-END:variables

}